
all: clean compile run

compile:
	#javac -Xlint:cast,deprecation,divzero,empty,fallthrough,finally,overrides,path,serial,unchecked *.java
	javac *.java

run:
	java SharedResourceAccess

clean:
	rm -f *~
	rm -f *.class
